-- migrate:up
CREATE TABLE _users
(
  "ID" BIGSERIAL PRIMARY KEY NOT NULL,
  "NAME" VARCHAR(255) NOT NULL,
  "USERNAME" VARCHAR(255) NOT NULL,
  "PASSWORD" VARCHAR(255) NOT NULL,
  "ROLE" VARCHAR(255) NOT NULL,
  "CREATED_AT" TIMESTAMPTZ DEFAULT NOW()
);

-- migrate:down
DROP TABLE IF EXISTS _users;
