-- migrate:up
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE _transaction_details
(
    "ID" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "TRANSACTION_ID" UUID NOT NULL,
    "PRODUCT_ID" UUID NOT NULL,
    "PRODUCT_NAME" VARCHAR(255) NOT NULL,
    "QUANTITY" INT NOT NULL CHECK ("QUANTITY" > 0),
    "PRICE" NUMERIC(15,2) NOT NULL,
    "SUBTOTAL" NUMERIC(15,2) NOT NULL,
    "CREATED_AT" TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY ("TRANSACTION_ID") REFERENCES _transactions("ID") ON DELETE CASCADE,
    FOREIGN KEY ("PRODUCT_ID") REFERENCES _products("ID") ON DELETE CASCADE
);

-- migrate:down
DROP TABLE IF EXISTS _transaction_details;
DROP EXTENSION IF EXISTS "uuid-ossp";